name: PinPutExample
description: PinPut Example
version: 0.0.1
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  pinput:
    path: ../ #^0.1.2 #add latest
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
