addons: 
  apt: 
    packages: 
      - libstdc++6
      - fonts-droid
    sources: 
      - ubuntu-toolchain-r-test
before_script: 
  - "git clone https://github.com/flutter/flutter.git -b beta"
  - "./flutter/bin/flutter doctor"
cache: 
  directories: 
    - $HOME/.pub-cache
dart_task: "-dartfmt -dartanalyzer"
language: dart
os: 
  - linux
sudo: false
