name: pinput
description: This widget keeps whole width of parent widget and layouts textfields in a way to create PIN code input field look it accepts string of any length and calls the onSubmit method when all fields are filled.
version: 0.1.3
author: Tornike Qurdadze <qurdadzze@gmail.com>
homepage: https://github.com/Tkko/Flutter_PinPut

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
